app_name: confirmation-statement-api
group: api

weight: 90
routes:
  1: ^/transactions/(.*)/confirmation-statement/*
  2: ^/confirmation-statement/*
  3: ^/private/confirmation-statement/*
  4: ^/private/transactions/(.*)/confirmation-statement/(.*)/filings