package uk.gov.companieshouse.confirmationstatementapi.eligibility;

public enum EligibilityStatusCode {
    INVALID_COMPANY_APPOINTMENTS_MORE_THAN_ONE_OFFICER,
    INVALID_COMPANY_APPOINTMENTS_MORE_THAN_ONE_PSC,
    INVALID_COMPANY_STATUS,
    INVALID_COMPANY_TYPE_CS01_FILING_NOT_REQUIRED,
    INVALID_COMPANY_TYPE_PAPER_FILING_ONLY,
    INVALID_COMPANY_TYPE_USE_WEB_FILING,
    COMPANY_NOT_FOUND,
    COMPANY_VALID_FOR_SERVICE
}
